### ISSUE TITLE
Error: python basicsr/test.py -opt options/test/benchmark_BSRN_x4.yml

### ISSUE THREAD

**Issue by nandubeigu** [xiaom233/BSRN#11]
2023-03-06 09:55:28,820 INFO: Dataset [PairedImageDataset] - Set5 is built.
2023-03-06 09:55:28,820 INFO: Number of test images in Set5: 5
2023-03-06 09:55:28,821 INFO: Dataset [PairedImageDataset] - Set14 is built.
2023-03-06 09:55:28,821 INFO: Number of test images in Set14: 14
Name BSRN is not found, use name: BSRN_basicsr!
Traceback (most recent call last):
  File "basicsr/test.py", line 45, in <module>
    test_pipeline(root_path)
  File "basicsr/test.py", line 35, in test_pipeline
    model = build_model(opt)
  File "/root/miniconda3/lib/python3.8/site-packages/basicsr/models/__init__.py", line 26, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/root/miniconda3/lib/python3.8/site-packages/basicsr/models/sr_model.py", line 22, in __init__
    self.net_g = build_network(opt['network_g'])
  File "/root/miniconda3/lib/python3.8/site-packages/basicsr/archs/__init__.py", line 22, in build_network
    net = ARCH_REGISTRY.get(network_type)(**opt)
  File "/root/miniconda3/lib/python3.8/site-packages/basicsr/utils/registry.py", line 70, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'BSRN' found in 'arch' registry!"

**Comment by lkyf** [comment]
> 2023-03-06 09:55:28,820 INFO: Dataset [PairedImageDataset] - Set5 is built. 2023-03-06 09:55:28,820 INFO: Number of test images in Set5: 5 2023-03-06 09:55:28,821 INFO: Dataset [PairedImageDataset] - Set14 is built. 2023-03-06 09:55:28,821 INFO: Number of test images in Set14: 14 Name BSRN is not found, use name: BSRN_basicsr! Traceback (most recent call last): File "basicsr/test.py", line 45, in test_pipeline(root_path) File "basicsr/test.py", line 35, in test_pipeline model = build_model(opt) File "/root/miniconda3/lib/python3.8/site-packages/basicsr/models/**init**.py", line 26, in build_model model = MODEL_REGISTRY.get(opt['model_type'])(opt) File "/root/miniconda3/lib/python3.8/site-packages/basicsr/models/sr_model.py", line 22, in **init** self.net_g = build_network(opt['network_g']) File "/root/miniconda3/lib/python3.8/site-packages/basicsr/archs/**init**.py", line 22, in build_network net = ARCH_REGISTRY.get(network_type)(**opt) File "/root/miniconda3/lib/python3.8/site-packages/basicsr/utils/registry.py", line 70, in get raise KeyError(f"No object named '{name}' found in '{self._name}' registry!") KeyError: "No object named 'BSRN' found in 'arch' registry!"

same problem, how do you fix it?

**Comment by anewusername77** [comment]
me too,how to fix?
